name: "Secret Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  secret-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Vollständige Git-Historie für umfassenden Scan

    - name: Gitleaks Secret Detection
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: TruffleHog Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --only-verified

    - name: Check for Common Secret Patterns
      run: |
        echo "Scanning for common secret patterns..."

        # Prüfe auf API Keys
        if grep -rE "api[_-]?key.*['\"]([a-zA-Z0-9_-]{20,})['\"]" --include="*.html" --include="*.js" . 2>/dev/null; then
          echo "⚠️ Possible API key found!"
          exit 1
        fi

        # Prüfe auf Passwörter
        if grep -rE "password.*['\"]([^'\"]{8,})['\"]" --include="*.html" --include="*.js" . 2>/dev/null; then
          echo "⚠️ Possible hardcoded password found!"
          exit 1
        fi

        # Prüfe auf Tokens
        if grep -rE "token.*['\"]([a-zA-Z0-9_-]{20,})['\"]" --include="*.html" --include="*.js" . 2>/dev/null; then
          echo "⚠️ Possible token found!"
          exit 1
        fi

        # Prüfe auf AWS Keys
        if grep -rE "AKIA[0-9A-Z]{16}" --include="*.html" --include="*.js" . 2>/dev/null; then
          echo "⚠️ Possible AWS key found!"
          exit 1
        fi

        # Prüfe auf Private Keys
        if grep -rE "-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----" --include="*.html" --include="*.js" --include="*.pem" . 2>/dev/null; then
          echo "⚠️ Private key found!"
          exit 1
        fi

        echo "✅ No common secret patterns detected"

    - name: Scan for Environment Variables
      run: |
        echo "Checking for exposed environment variables..."

        if grep -rE "process\.env\.[A-Z_]+" --include="*.js" . 2>/dev/null; then
          echo "⚠️ Environment variables found - review manually"
        else
          echo "✅ No environment variables exposed"
        fi
